name: CI

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Env
        run: |
          echo "export BRANCH=$(echo ${GITHUB_REF} | tr '/' '\n' | tail -1)" >> .env
          source .env
      - name: Install Terraform
        run: |
          sudo rm -f /usr/local/bin/terraform
          wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
          sudo unzip ./terraform_0.11.14_linux_amd64.zip -d /usr/local/bin/
          sudo rm -f ./terraform_0.11.14_linux_amd64.zip
          terraform -v
      - name: Setup GCP Service Accounts
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT }}| base64 --decode > /tmp/gcp-service-account.json
          echo "export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account.json" >> .env
          echo "export GOOGLE_CREDENTIALS=/tmp/gcp-service-account.json" >> .env
      - name: Setup Terraform Vars
        run: |
          echo "export TF_VAR_slack_hook=${{ secrets.SLACK_HOOK }}" >> .env
          echo "export TF_VAR_slack_channel=${{ secrets.SLACK_CHANNEL }}" >> .env
          echo "export TF_VAR_support_email=${{ secrets.SUPPORT_EMAIL }}" >> .env
      - uses: actions/checkout@v1
      - name: Init Terraform
        run: |
          source .env
          terraform init
      - name: Validate Terraform Configuration
        run: |
          source .env
          terraform validate
      - name: Apply Terraform
        run: |
          source .env
          terraform apply -auto-approve
