name: CI

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Env
        run: |
          echo "export BRANCH=$(echo ${GITHUB_REF} | tr '/' '\n' | tail -1)" >> .env
          source .env
          echo $BRANCH
      - name: Install Terraform
        run: |
          sudo rm -f /usr/local/bin/terraform
          wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
          sudo unzip ./terraform_0.11.14_linux_amd64.zip -d /usr/local/bin/
          sudo rm -f ./terraform_0.11.14_linux_amd64.zip
          terraform -v
      - name: Setup GCP Service Accounts
        run: |
          echo "$GCP_SERVICE_ACCOUNT" | base64 --decode > /tmp/gcp-service-account.json
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: actions/checkout@v1
      - name: Init Terraform
        run: |
          terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-service-account.json
          GOOGLE_CREDENTIALS: /tmp/gcp-service-account.json
      - name: Validate Terraform Configuration
        run: |
          terraform validate
        env:
          TF_VAR_slack_hook: ${{ secrets.SLACK_HOOK }}
          TF_VAR_slack_channel: ${{ secrets.SLACK_CHANNEL }}
          TF_VAR_support_email: ${{ secrets.SUPPORT_EMAIL }}
      - name: Print branch
        run: echo $BRANCH
      - name: Apply Terraform
        run: |
          terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-service-account.json
          GOOGLE_CREDENTIALS: /tmp/gcp-service-account.json
          TF_VAR_slack_hook: ${{ secrets.SLACK_HOOK }}
          TF_VAR_slack_channel: ${{ secrets.SLACK_CHANNEL }}
          TF_VAR_support_email: ${{ secrets.SUPPORT_EMAIL }}
